## code to prepare `internal` dataset goes here

condition_dependencies <- list(
  none = c(
    "is present", "is in the DOM", "doesn't exist", "is not present",
    "is not in the DOM", "is missing", "is absent",
    "is visible", "is displayed", "is not visible", "is not displayed",
    "is hidden", "is invisible", "is enabled", "is not enabled", "is disabled"
  ),
  name = c("has tag name", "does not have tag name"),
  text = c("has text", "has exact text", "does not have text", "does not have exact text"),
  attribute = c("has attr", "attr contains", "does not have attr", "does not have exact attr"),
  value = c("has value", "does not have value"),
  css = c("has css property", "does not have css property"),
  length = c("has length", "does not have length", "has at least", "does not have at least")
)

# Adapted from:
# https://github.com/puppeteer/puppeteer/blob/1f08c54d837daf9a4dc76d3e0881ed7eb837ad66/packages/puppeteer-core/src/common/USKeyboardLayout.ts
chromote_key_definitions <- list(
  '0' = list(windowsVirtualKeyCode = 48, key = '0', code = 'Digit0'),
  '1' = list(windowsVirtualKeyCode = 49, key = '1', code = 'Digit1'),
  '2' = list(windowsVirtualKeyCode = 50, key = '2', code = 'Digit2'),
  '3' = list(windowsVirtualKeyCode = 51, key = '3', code = 'Digit3'),
  '4' = list(windowsVirtualKeyCode = 52, key = '4', code = 'Digit4'),
  '5' = list(windowsVirtualKeyCode = 53, key = '5', code = 'Digit5'),
  '6' = list(windowsVirtualKeyCode = 54, key = '6', code = 'Digit6'),
  '7' = list(windowsVirtualKeyCode = 55, key = '7', code = 'Digit7'),
  '8' = list(windowsVirtualKeyCode = 56, key = '8', code = 'Digit8'),
  '9' = list(windowsVirtualKeyCode = 57, key = '9', code = 'Digit9'),
  '\r' = list(windowsVirtualKeyCode = 13, code = 'Enter', key = 'Enter', text = '\r'),
  '\n' = list(windowsVirtualKeyCode = 13, code = 'Enter', key = 'Enter', text = '\r'),
  ' ' = list(windowsVirtualKeyCode = 32, key = ' ', code = 'Space'),
  a = list(windowsVirtualKeyCode = 65, key = 'a', code = 'KeyA'),
  b = list(windowsVirtualKeyCode = 66, key = 'b', code = 'KeyB'),
  c = list(windowsVirtualKeyCode = 67, key = 'c', code = 'KeyC'),
  d = list(windowsVirtualKeyCode = 68, key = 'd', code = 'KeyD'),
  e = list(windowsVirtualKeyCode = 69, key = 'e', code = 'KeyE'),
  f = list(windowsVirtualKeyCode = 70, key = 'f', code = 'KeyF'),
  g = list(windowsVirtualKeyCode = 71, key = 'g', code = 'KeyG'),
  h = list(windowsVirtualKeyCode = 72, key = 'h', code = 'KeyH'),
  i = list(windowsVirtualKeyCode = 73, key = 'i', code = 'KeyI'),
  j = list(windowsVirtualKeyCode = 74, key = 'j', code = 'KeyJ'),
  k = list(windowsVirtualKeyCode = 75, key = 'k', code = 'KeyK'),
  l = list(windowsVirtualKeyCode = 76, key = 'l', code = 'KeyL'),
  m = list(windowsVirtualKeyCode = 77, key = 'm', code = 'KeyM'),
  n = list(windowsVirtualKeyCode = 78, key = 'n', code = 'KeyN'),
  o = list(windowsVirtualKeyCode = 79, key = 'o', code = 'KeyO'),
  p = list(windowsVirtualKeyCode = 80, key = 'p', code = 'KeyP'),
  q = list(windowsVirtualKeyCode = 81, key = 'q', code = 'KeyQ'),
  r = list(windowsVirtualKeyCode = 82, key = 'r', code = 'KeyR'),
  s = list(windowsVirtualKeyCode = 83, key = 's', code = 'KeyS'),
  t = list(windowsVirtualKeyCode = 84, key = 't', code = 'KeyT'),
  u = list(windowsVirtualKeyCode = 85, key = 'u', code = 'KeyU'),
  v = list(windowsVirtualKeyCode = 86, key = 'v', code = 'KeyV'),
  w = list(windowsVirtualKeyCode = 87, key = 'w', code = 'KeyW'),
  x = list(windowsVirtualKeyCode = 88, key = 'x', code = 'KeyX'),
  y = list(windowsVirtualKeyCode = 89, key = 'y', code = 'KeyY'),
  z = list(windowsVirtualKeyCode = 90, key = 'z', code = 'KeyZ'),
  '*' = list(windowsVirtualKeyCode = 106, key = '*', code = 'NumpadMultiply', location = 3),
  '+' = list(windowsVirtualKeyCode = 107, key = '+', code = 'NumpadAdd', location = 3),
  '-' = list(windowsVirtualKeyCode = 109, key = '-', code = 'NumpadSubtract', location = 3),
  '/' = list(windowsVirtualKeyCode = 111, key = '/', code = 'NumpadDivide', location = 3),
  ';' = list(windowsVirtualKeyCode = 186, key = ';', code = 'Semicolon'),
  '=' = list(windowsVirtualKeyCode = 187, key = '=', code = 'Equal'),
  ',' = list(windowsVirtualKeyCode = 188, key = ',', code = 'Comma'),
  '.' = list(windowsVirtualKeyCode = 190, key = '.', code = 'Period'),
  '`' = list(windowsVirtualKeyCode = 192, key = '`', code = 'Backquote'),
  '[' = list(windowsVirtualKeyCode = 219, key = '[', code = 'BracketLeft'),
  '\\' = list(windowsVirtualKeyCode = 220, key = '\\', code = 'Backslash'),
  ']' = list(windowsVirtualKeyCode = 221, key = ']', code = 'BracketRight'),
  "'" = list(windowsVirtualKeyCode = 222, key = "'", code = 'Quote'),
  ')' = list(windowsVirtualKeyCode = 48, key = ')', code = 'Digit0'),
  '!' = list(windowsVirtualKeyCode = 49, key = '!', code = 'Digit1'),
  '@' = list(windowsVirtualKeyCode = 50, key = '@', code = 'Digit2'),
  '#' = list(windowsVirtualKeyCode = 51, key = '#', code = 'Digit3'),
  '$' = list(windowsVirtualKeyCode = 52, key = '$', code = 'Digit4'),
  '%' = list(windowsVirtualKeyCode = 53, key = '%', code = 'Digit5'),
  '^' = list(windowsVirtualKeyCode = 54, key = '^', code = 'Digit6'),
  '&' = list(windowsVirtualKeyCode = 55, key = '&', code = 'Digit7'),
  '(' = list(windowsVirtualKeyCode = 57, key = '(', code = 'Digit9'),
  A = list(windowsVirtualKeyCode = 65, key = 'A', code = 'KeyA'),
  B = list(windowsVirtualKeyCode = 66, key = 'B', code = 'KeyB'),
  C = list(windowsVirtualKeyCode = 67, key = 'C', code = 'KeyC'),
  D = list(windowsVirtualKeyCode = 68, key = 'D', code = 'KeyD'),
  E = list(windowsVirtualKeyCode = 69, key = 'E', code = 'KeyE'),
  F = list(windowsVirtualKeyCode = 70, key = 'F', code = 'KeyF'),
  G = list(windowsVirtualKeyCode = 71, key = 'G', code = 'KeyG'),
  H = list(windowsVirtualKeyCode = 72, key = 'H', code = 'KeyH'),
  I = list(windowsVirtualKeyCode = 73, key = 'I', code = 'KeyI'),
  J = list(windowsVirtualKeyCode = 74, key = 'J', code = 'KeyJ'),
  K = list(windowsVirtualKeyCode = 75, key = 'K', code = 'KeyK'),
  L = list(windowsVirtualKeyCode = 76, key = 'L', code = 'KeyL'),
  M = list(windowsVirtualKeyCode = 77, key = 'M', code = 'KeyM'),
  N = list(windowsVirtualKeyCode = 78, key = 'N', code = 'KeyN'),
  O = list(windowsVirtualKeyCode = 79, key = 'O', code = 'KeyO'),
  P = list(windowsVirtualKeyCode = 80, key = 'P', code = 'KeyP'),
  Q = list(windowsVirtualKeyCode = 81, key = 'Q', code = 'KeyQ'),
  R = list(windowsVirtualKeyCode = 82, key = 'R', code = 'KeyR'),
  S = list(windowsVirtualKeyCode = 83, key = 'S', code = 'KeyS'),
  T = list(windowsVirtualKeyCode = 84, key = 'T', code = 'KeyT'),
  U = list(windowsVirtualKeyCode = 85, key = 'U', code = 'KeyU'),
  V = list(windowsVirtualKeyCode = 86, key = 'V', code = 'KeyV'),
  W = list(windowsVirtualKeyCode = 87, key = 'W', code = 'KeyW'),
  X = list(windowsVirtualKeyCode = 88, key = 'X', code = 'KeyX'),
  Y = list(windowsVirtualKeyCode = 89, key = 'Y', code = 'KeyY'),
  Z = list(windowsVirtualKeyCode = 90, key = 'Z', code = 'KeyZ'),
  ':' = list(windowsVirtualKeyCode = 186, key = ' =', code = 'Semicolon'),
  '<' = list(windowsVirtualKeyCode = 188, key = '<', code = 'Comma'),
  '_' = list(windowsVirtualKeyCode = 189, key = '_', code = 'Minus'),
  '>' = list(windowsVirtualKeyCode = 190, key = '>', code = 'Period'),
  '?' = list(windowsVirtualKeyCode = 191, key = '?', code = 'Slash'),
  '~' = list(windowsVirtualKeyCode = 192, key = '~', code = 'Backquote'),
  '{' = list(windowsVirtualKeyCode = 219, key = '{', code = 'BracketLeft'),
  '|' = list(windowsVirtualKeyCode = 220, key = '|', code = 'Backslash'),
  '}' = list(windowsVirtualKeyCode = 221, key = '}', code = 'BracketRight'),
  '"' = list(windowsVirtualKeyCode = 222, key = '"', code = 'Quote')
)

usethis::use_data(condition_dependencies, chromote_key_definitions, internal = TRUE, overwrite = TRUE)
